### PR TITLE
Handle system exit otherwise the script does not read results

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
@pacospace it looks like the script also runs virtual environment which prints some stuff to stdout... :(

**Comment by fridex** [comment]
> @pacospace it looks like the script also runs virtual environment which prints some stuff to stdout... :(

Hm... test this one :wink:

**Comment by pacospace** [comment]
> > @pacospace it looks like the script also runs virtual environment which prints some stuff to stdout... :(
> 
> Hm... test this one

I'm still not able to get the proper result of the PI :)

**Comment by fridex** [comment]
> > > @pacospace it looks like the script also runs virtual environment which prints some stuff to stdout... :(
> > 
> > 
> > Hm... test this one
> 
> I'm still not able to get the proper result of the PI :)

Yup, still some stuff printed to stdout...

**Comment by pacospace** [comment]
> > > > @pacospace it looks like the script also runs virtual environment which prints some stuff to stdout... :(
> > > 
> > > 
> > > Hm... test this one
> > 
> > 
> > I'm still not able to get the proper result of the PI :)
> 
> Yup, still some stuff printed to stdout...

I included your changes in https://github.com/thoth-station/performance/pull/32 :) Thanks @fridex :beers:

**Pull request closed without merging**
